import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { renderMarkdown } from '../src/render.js';
import { scanRepo } from '../src/scan.js';

describe('renderMarkdown', () => {
  it('renders concise evidence-linked markdown', async () => {
    const primer = await scanRepo('fixtures/node-cli', { deterministicTime: true });
    const markdown = renderMarkdown(primer);

    assert.match(markdown, /^# Agent Primer: fixture-node-cli/);
    assert.match(markdown, /npm run test/);
    assert.match(markdown, /package\.json/);
    assert.match(markdown, /Generated by agentprimer/);
  });
});
