import type { Evidence, RepoPrimer, SuggestedTask } from './types.js';

export function renderJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

export function renderMarkdown(primer: RepoPrimer): string {
  const lines: string[] = [];
  lines.push(`# Agent Primer: ${primer.name}`, '');
  lines.push(primer.summary, '');
  lines.push('## Stack Signals', '');
  lines.push(`- Languages: ${listOrNone(primer.languages)}`);
  lines.push(`- Frameworks: ${listOrNone(primer.frameworks)}`);
  lines.push(`- Package manager: ${primer.packageManager ?? 'none detected'}`, '');
  lines.push('## Commands', '');
  if (primer.commands.length === 0) {
    lines.push('- No common commands detected.');
  } else {
    for (const command of primer.commands) {
      lines.push(`- \`${command.command}\` — ${command.confidence} confidence (${formatEvidence(command.evidence)})`);
    }
  }
  lines.push('', '## Likely Entry Points', '');
  pushEvidence(lines, primer.entryPoints, 'No obvious entry points detected.');
  lines.push('', '## Conventions And Docs', '');
  pushEvidence(lines, primer.conventions, 'No explicit repo convention files detected.');
  lines.push('', '## Config Surface', '');
  pushEvidence(lines, primer.configs, 'No common config files detected.');
  lines.push('', '## Risks', '');
  pushEvidence(lines, primer.risks, 'No obvious high-risk areas detected.');
  lines.push('', '## Onboarding Gaps', '');
  pushEvidence(lines, primer.gaps, 'No obvious onboarding gaps detected.');
  lines.push('', '## Layout Snapshot', '');
  pushEvidence(lines, primer.layout.slice(0, 20), 'Flat or sparse repository.');
  lines.push('', '## Scan Notes', '');
  lines.push(`- Ignored directories: ${listOrNone(primer.ignoredDirectories)}`);
  lines.push('', '<!-- Generated by agentprimer. Local-only scan; review before sharing. -->', '');
  return lines.join('\n');
}

export function renderSuggestedTask(task: SuggestedTask): string {
  return [
    `# Suggested First Task: ${task.title}`,
    '',
    `- Risk: ${task.risk}`,
    `- Rationale: ${task.rationale}`,
    `- Evidence: ${formatEvidence(task.evidence)}`,
    ''
  ].join('\n');
}

function pushEvidence(lines: string[], evidence: Evidence[], empty: string): void {
  if (evidence.length === 0) {
    lines.push(`- ${empty}`);
    return;
  }

  for (const item of evidence) {
    lines.push(`- ${item.path}${item.detail ? ` — ${item.detail}` : ''}`);
  }
}

function formatEvidence(evidence: Evidence[]): string {
  return evidence.map((item) => item.detail ? `${item.path}: ${item.detail}` : item.path).join('; ');
}

function listOrNone(values: string[]): string {
  return values.length > 0 ? values.join(', ') : 'none detected';
}
